### PR TITLE
fix issue 371: incorrect doc state after undo

### LINKED ISSUE #371: UndoManager: incorrect undo result
Hi,

Below the code that reproduces the problem. 

`

        let d = Doc::new();

        let r = d.get_or_insert_map("r");
        let s1 = r.insert(&mut d.transact_mut(), "s1", MapPrelim::<i32>::new());
        let b1_arr = s1.insert(&mut d.transact_mut(), "b1", ArrayPrelim::default());
        let el1 = b1_arr.insert(&mut d.transact_mut(), 0, MapPrelim::<i32>::new());
        el1.insert(&mut d.transact_mut(), "f1", 8);
        el1.insert(&mut d.transact_mut(), "f2", true);
        println!("Before undo manager: {}", r.to_json(&d.transact()));

        let mut mgr = UndoManager::with_options(&d, &r, Options::default());
        let mut txn = d.transact_mut();
        let el0 = b1_arr.insert(&mut txn, 0, MapPrelim::<i32>::new());
        el0.insert(&mut txn, "f1", 8);
        el0.insert(&mut txn, "f2", false);

        el1.insert(&mut txn, "f1", 13);
        el1.remove(&mut txn, "f2");
        drop(txn);
        mgr.reset();
        println!("After txn 1: {}", r.to_json(&d.transact()));

        let mut txn = d.transact_mut();
        el1.insert(&mut txn, "f2", false);
        drop(txn);
        mgr.reset();
        println!("After txn 2: {}", r.to_json(&d.transact()));

        let mut txn = d.transact_mut();
        el1.insert(&mut txn, "f2", true);
        drop(txn);
        mgr.reset();
        println!("After txn 3: {}", r.to_json(&d.transact()));

        println!("Before undo sequence: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 1: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 2: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 3: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();

`

This produces the following result

Before undo manager: {s1: {b1: [{f2: true, f1: 8}]}}
After txn 1: {s1: {b1: [{f1: 8, f2: false}, {f1: 13}]}}
After txn 2: {s1: {b1: [{f2: false, f1: 8}, {f2: false, f1: 13}]}}
After txn 3: {s1: {b1: [{f1: 8, f2: false}, {f1: 13, f2: true}]}}
After undo 1: {s1: {b1: [{f2: false, f1: 8}, {f2: false, f1: 13}]}}
After undo 2: {s1: {b1: [{f1: 8, f2: false}, {f1: 13}]}}
After undo 3: {s1: {b1: [{f1: 8}]}}

As you can see in the last result key "f2" is lost.

### PR DESCRIPTION
**Pull request by Horusiath**
Fixes #371

### CODE REVIEW

File: yrs/src/block.rs [hunk 1]
```diff
@@ -285,12 +285,15 @@ impl ItemPtr {
                 // If it is intended to delete right while item is redone,
                 // we can expect that item should replace right.
                 while let Some(left_item) = left.as_deref() {
-                    if let Some(ptr) = left_item.right {
-                        let id = ptr.id();
-                        if items_to_delete.is_deleted(id) || s1.is_deleted(id) || s2.is_deleted(id)
+                    if let Some(left_right) = left_item.right {
+                        let id = left_right.id();
+                        if left_right.redone.is_some()
```
Comment (Horusiath) [inline yrs/src/block.rs:290]: This was a missing check (present in yjs), that caused an issue.
