### PR TITLE
Fixed Text::remove_range for even/odd-byte length chars

### LINKED ISSUE #156: Delete multi-byte character from text will cause panic
Hi,
I'm unsure if I misused the API. 
Should the ```len``` value pass to ```text::remove_range()``` correspond to the ```offset_kind``` of doc?

To Reproduce
```Rust
// yrs = "0.10.2"
// lib0 = "0.10.2"

use yrs::{
    types::text::*,
    Doc
};

#[test]
fn reproduce() {
    let doc = Doc::new();
    let mut txn = doc.transact();
    let txt = txn.get_text("test");

    txt.insert(&mut txn, 0, "😭😊");
    txt.remove_range(&mut txn, 0, "😭".len() as u32);

    assert_eq!(txt.to_string().as_str(), "😊");
}
```
```
thread 'reproduce' panicked at 'byte index 2 is not a char boundary; it is inside '😭' (bytes 0..4) of `😭😊`'
```

### PR DESCRIPTION
**Pull request by Horusiath**
Fixes #156 (hopefully permanently this time).

### CODE REVIEW

File: yrs/src/block.rs [hunk 1]
```diff
@@ -1137,12 +1138,12 @@ impl SplittableString {
...
         let mut i = 0;
-        for c in self.content.encode_utf16() {
+        for c in self.content.chars() {
             if i >= offset {
                 break;
             }
-            off += if c < 0x80 { 1 } else { 2 };
-            i += 1;
+            off += c.len_utf8() as u32;
+            i += c.len_utf16() as u32;
```
Comment (Horusiath) [inline yrs/src/block.rs:1146]: Offset provided in this method is UTF-16 aligned (since its unit of measure for Yjs `item.id.clock`), while we need to convert it to UTF-8 aligned (since it's the index for Rust's string splitting).

File: yrs/src/block.rs [hunk 2]
```diff
@@ -1112,13 +1112,14 @@ impl SplittableString {
...
+                // characters - we're computing by characters
+                for c in self.content.chars() {
                     if remaining == 0 {
                         break;
                     }
-                    let utf8_len = if c < 0x80 { 1 } else { 2 };
-                    remaining -= utf8_len;
-                    i += 1;
+                    remaining -= c.len_utf8() as u32;
+                    i += c.len_utf16() as u32;
```
Comment (Horusiath) [inline yrs/src/block.rs:1122]: Here we're mapping offset provided by user in UTF-8 bytes (`OffsetKind::Bytes`), while what we need to return is a value provided in UTF-16 (since its unit of measure for Yjs item.id.clock).
